oem: "Infinix"
device: "Infinix-X6876"
model: "Infinix GT 30"

variants:
  - variant: "Global"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6876-OP"
    incremental: "201500013"

  - variant: "India"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6876-IN"
    incremental: "201500013"

  - variant: "Russia"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6876-RU"
    incremental: "201500013"
