oem: "Infinix"
device: "Infinix-X6873"
model: "Infinix GT 30 Pro"

variants:
  - variant: "Global"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6873-OP"
    incremental: "201500011"

  - variant: "India"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6873-IN"
    incremental: "201500011"

  - variant: "Russia"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6873-RU"
    incremental: "201500011"

  - variant: "Turkey"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "X6873-TR"
    incremental: "201500011"

  - variant: "Europe"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "X6873-EU"
    incremental: "131015"
