oem: "TECNO"
device: "TECNO-LJ8k"
android_version: "15"
build_tag: "AP3A.240905.015.A2"
model: "TECNO POVA Curve 5G"

variants:
  - variant: "Global"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "LJ8k-OP"
    incremental: "180003"

  - variant: "India"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "LJ8k-IN"
    incremental: "180003"
