oem: "TECNO"
device: "TECNO-KJ8"
android_version: "14"
build_tag: "UP1A.231005.007"
model: "TECNO SPARK 20 Pro 5G"

variants:
  - variant: "Global"
    product: "KJ8-OP"
    incremental: "250108V1200"

  - variant: "India"
    android_version: "14"
    build_tag: "UP1A.231005.007"
    product: "KJ8-IN"
    incremental: "260410V1339"
