oem: "TECNO"
device: "TECNO-CM7"
model: "TECNO CAMON 40 Pro 5G"

variants:
  - variant: "Global"
    android_version: "16"
    build_tag: "BP2A.250605.031.A3"
    product: "CM7-OP"
    incremental: "201500011"

  - variant: "Turkey"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "CM7-TR"
    incremental: "165004"
