oem: "TECNO"
device: "TECNO-LJ8"
model: "TECNO POVA 7 Pro 5G"

variants:
  - variant: "Global"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "LJ8-OP"
    incremental: "145007"

  - variant: "Russia"
    android_version: "15"
    build_tag: "AP3A.240905.015.A2"
    product: "LJ8-RU"
    incremental: "180001"
